### ISSUE TITLE
Provide ability to ignore certain files

### ISSUE THREAD

**Issue by lohengrin332** [barwin/App-GitHooks-Plugin-PreventTrailingWhitespace#1]
The use case here is that a generated file has whitespace at line endings, but needs to be committed.  It would be great if this were similar to how .gitignore works.

**Comment by barwin** [comment]
@lohengrin332 - I've been thinking about this, and trying to think of the most sane way to implement.

Would you want to skip _all_ hooks for such files? If so, I think the parent App-GitHooks project should support such a ".gitignore" style file.

Having a ".gitignore" file for each App-GitHooks plugin could get unruly so I hesitate to go down that path.

However, the plugins can already be configured from the global config file.  Perhaps we could support an 'ignored' directive there. E.g.

```
[PreventTrailingWhitespace]
ignored = some, list, of, files, or, dirs, or, /regexes/
```

Thoughts?

**Comment by lohengrin332** [comment]
@barwin - I originally had in mind to skip all git hooks based on the contents of a .gitignore file, but your suggestion would probably be better.
